version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
    # Build Docker image
      - docker build . -t $RepositoryName:$Commit_ID
    # Tag image with commit ID
      - docker tag $RepositoryName:$Commit_ID $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$RepositoryName:$Commit_ID
    # Push image to ECR
      - docker push $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$RepositoryName:$Commit_ID
