version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - python -c 'print("This is a integration test stage")'
