version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      # Build Docker image
      - docker pull $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$RepositoryName:$Commit_ID
      # Tag image with commit ID
      - docker tag $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$RepositoryName:$Commit_ID $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$RepositoryName:latest
      # Push image to ECR
      - docker push $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$RepositoryName
      # Save installation package on S3 
      - docker save -o $RepositoryName-$Commit_ID.tar $Account_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$RepositoryName:latest
      - aws s3 cp $RepositoryName-$Commit_ID.tar s3://$RepositoryName-build-artifacts/$RepositoryName/package/
